# Generated by Django 6.1 on 2026-09-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='题目')),
                ('option_a', models.CharField(max_length=200, verbose_name='选项 A')),
                ('option_b', models.CharField(max_length=200, verbose_name='选项 B')),
                ('option_c', models.CharField(max_length=200, verbose_name='选项 C')),
                ('option_d', models.CharField(max_length=200, verbose_name='选项 D')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正确答案')),
                ('time_limit', models.PositiveIntegerField(default=20, verbose_name='答题时限(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='房间号')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='房间名称')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('playing', '答题中'), ('leaderboard', '排行榜'), ('ended', '已结束')], default='waiting', max_length=20)),
                ('current_question_index', models.IntegerField(default=-1)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('score', models.IntegerField(default=0)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
            ],
            options={
                'unique_together': {('room', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.room')),
            ],
            options={
                'unique_together': {('player', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RoomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_questions', to='game.room')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('room', 'question')},
            },
        ),
    ]
