# Generated by Django 6.1 on 2026-09-01 14:39

import game.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', validators=[game.validators.validate_question_image], verbose_name='题目图片'),
        ),
    ]
