# Generated by Django 6.1 on 2026-09-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题')], default='single', max_length=10, verbose_name='题型'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=10, verbose_name='正确答案'),
        ),
    ]
