# Generated by Django 6.1 on 2026-09-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judgment', '判断题')], default='single', max_length=10, verbose_name='题型'),
        ),
    ]
