# Generated by Django 6.1 on 2026-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_question_judgment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judgment', '判断题'), ('short_answer', '简答题'), ('word_cloud', '词云题')], default='single', max_length=20, verbose_name='题型'),
        ),
    ]
