# Generated by Django 6.1 on 2026-09-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_answer_selected_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='TeacherInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='邀请码')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='可用次数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='公开题库'),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.teacher'),
        ),
        migrations.AddField(
            model_name='room',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='game.teacher'),
        ),
    ]
