# Generated by Django 6.1 on 2026-09-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_quizset_quizsetquestion_room_source_quiz_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='{"face":0,"hair":0}', max_length=120, verbose_name='个性化头像'),
        ),
    ]
